### ISSUE TITLE
Doesn't work with VSCode 1.95.0

### ISSUE THREAD

**Issue by cooldevdotcodes** [blackmann/fonted#10]
I've just updated VSCode to v1.95.0 and got this error message when trying to enable **fonted**

<img width="260" alt="Screenshot 2024-10-30 at 1 15 53 AM" src="https://github.com/user-attachments/assets/a1b48c77-7115-4356-817d-42614adbfd54">

```
Version: 1.95.0
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by Kowalskix1** [comment]
the same error

**Comment by kiraYuukiAsuna** [comment]
This is caused by the changes of vscode workbench.esm.html being renamed to workbench.html. So you can go to fonted extension install folder (On windows typically located at C:\Users\YourUserName\.vscode\extensions\degreat.fonted-1.0.0\out). open extension.js, searching for workbench.esm.html and change to workbench.html. Reopen vscode and try again. It works.

**Comment by blackmann** [comment]
At this point, vscode is probably playing hide-and-seek. Earlier this month, they changed the path to `workbench.esm.html`.

I have deployed a fix and should be available in a few minutes to all

**Comment by cooldevdotcodes** [comment]
> At this point, vscode is probably playing hide-and-seek. Earlier this month, they changed the path to `workbench.esm.html`.
> 
> I have deployed a fix and should be available in a few minutes to all

Thank you very much. It was fixed and work properly :-)

**Comment by cooldevdotcodes** [comment]
Thank you very much. It was fixed and work properly :-)
